
package com.training;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherService", targetNamespace = "http://ifaces.training.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.training.Weather
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ifaces.training.com/WeatherService/getWeatherByCityRequest", output = "http://ifaces.training.com/WeatherService/getWeatherByCityResponse")
    public Weather getWeatherByCity(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.training.WeatherWrapper
     */
    
}
